GET  http://localhost:8787/auth

###

POST http://localhost:8787/auth/registration
Content-Type: application/json

{
    "email": "Shivamshukla001@gmail.com",
    "password": "dhukq@#"
}

###

POST  http://localhost:8787/auth/login
Content-Type: application/json

{
    "email": "Shivamshukla001@gmail.com",
    "password": "dhukq@#"
}